"""empty message

Revision ID: 00cdd32fceae
Revises: 9e9f17c600eb
Create Date: 2021-01-19 21:04:16.235637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00cdd32fceae'
down_revision = '9e9f17c600eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backing_tracks', sa.Column('coda_number_of_bars', sa.Integer(), nullable=True))
    op.add_column('backing_tracks', sa.Column('intro_number_of_bars', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backing_tracks', 'intro_number_of_bars')
    op.drop_column('backing_tracks', 'coda_number_of_bars')
    # ### end Alembic commands ###
