"""empty message

Revision ID: 13e63a8f0720
Revises: 00cdd32fceae
Create Date: 2021-03-24 00:30:53.722408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e63a8f0720'
down_revision = '00cdd32fceae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backing_tracks', sa.Column('count_in', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backing_tracks', 'count_in')
    # ### end Alembic commands ###
