"""empty message

Revision ID: 1c040127f674
Revises: d119ce7cbc49
Create Date: 2019-01-25 23:35:20.488512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c040127f674'
down_revision = 'd119ce7cbc49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riff_exercise_items', sa.Column('octave', sa.Integer(), nullable=True))
    op.add_column('riff_exercise_items', sa.Column('pitch', sa.String(length=3), nullable=True))
    op.drop_column('riff_exercise_items', 'riff_root_key')
    op.add_column('riff_exercises', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.drop_column('riff_exercises', 'is_global')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riff_exercises', sa.Column('is_global', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('riff_exercises', 'is_public')
    op.add_column('riff_exercise_items', sa.Column('riff_root_key', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.drop_column('riff_exercise_items', 'pitch')
    op.drop_column('riff_exercise_items', 'octave')
    # ### end Alembic commands ###
