"""empty message

Revision ID: 1cd3b03edbe2
Revises: 13e63a8f0720
Create Date: 2021-03-27 00:31:35.133506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd3b03edbe2'
down_revision = '13e63a8f0720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backing_tracks', 'chord_info',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backing_tracks', 'chord_info',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
