"""empty message

Revision ID: 2a75401f7136
Revises: 99d16a0b769d
Create Date: 2017-12-16 00:49:59.929629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2a75401f7136"
down_revision = "99d16a0b769d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("riffs", sa.Column("render_date", sa.DateTime(), nullable=True))
    op.add_column("riffs", sa.Column("render_valid", sa.Boolean(), nullable=True))
    op.create_index(op.f("ix_riffs_id"), "riffs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_riffs_id"), table_name="riffs")
    op.drop_column("riffs", "render_valid")
    op.drop_column("riffs", "render_date")
    # ### end Alembic commands ###
