"""empty message

Revision ID: 2e8d1f0237ea
Revises: ad9b5f0b9acb
Create Date: 2018-11-13 23:01:22.236358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e8d1f0237ea'
down_revision = 'ad9b5f0b9acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riffs', sa.Column('multi_chord', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('riffs', 'multi_chord')
    # ### end Alembic commands ###
