"""empty message

Revision ID: 309e6a50a5d5
Revises: 8c6917cbd106
Create Date: 2018-11-10 20:00:20.376727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "309e6a50a5d5"
down_revision = "8c6917cbd106"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("riffs", sa.Column("backing_track_info", sa.JSON(), nullable=True))
    op.add_column("riffs", sa.Column("created_date", sa.DateTime(), nullable=True))
    op.add_column("riffs", sa.Column("multi_chord", sa.JSON(), nullable=True))
    op.add_column("riffs", sa.Column("scale_trainer_enabled", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("riffs", "scale_trainer_enabled")
    op.drop_column("riffs", "multi_chord")
    op.drop_column("riffs", "created_date")
    op.drop_column("riffs", "backing_track_info")
    # ### end Alembic commands ###
