"""empty message

Revision ID: 314daa387d52
Revises: 49bc99f4e27c
Create Date: 2019-06-25 00:38:05.174267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '314daa387d52'
down_revision = '49bc99f4e27c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backing_tracks',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tempo', sa.Integer(), nullable=True),
    sa.Column('chord_info', sa.String(), nullable=False),
    sa.Column('c_available', sa.Boolean(), nullable=False),
    sa.Column('cis_available', sa.Boolean(), nullable=False),
    sa.Column('d_available', sa.Boolean(), nullable=False),
    sa.Column('ees_available', sa.Boolean(), nullable=False),
    sa.Column('e_available', sa.Boolean(), nullable=False),
    sa.Column('f_available', sa.Boolean(), nullable=False),
    sa.Column('fis_available', sa.Boolean(), nullable=False),
    sa.Column('g_available', sa.Boolean(), nullable=False),
    sa.Column('aes_available', sa.Boolean(), nullable=False),
    sa.Column('a_available', sa.Boolean(), nullable=False),
    sa.Column('bes_available', sa.Boolean(), nullable=False),
    sa.Column('b_available', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backing_tracks_id'), 'backing_tracks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backing_tracks_id'), table_name='backing_tracks')
    op.drop_table('backing_tracks')
    # ### end Alembic commands ###
