"""empty message

Revision ID: 3757f595a977
Revises: f9e4b9a9d1e0
Create Date: 2019-03-09 15:09:44.081321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3757f595a977"
down_revision = "f9e4b9a9d1e0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("riff_exercises", sa.Column("modified_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("riff_exercises", "modified_at")
    # ### end Alembic commands ###
