"""empty message

Revision ID: 386683230f6d
Revises: aeadc83d259f
Create Date: 2019-01-26 20:34:05.427779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '386683230f6d'
down_revision = 'aeadc83d259f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('riff_exercise_items_created_by_fkey', 'riff_exercise_items', type_='foreignkey')
    op.drop_column('riff_exercise_items', 'created_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riff_exercise_items', sa.Column('created_by', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('riff_exercise_items_created_by_fkey', 'riff_exercise_items', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###
