"""empty message

Revision ID: 49bc99f4e27c
Revises: f0700fa6a3ea
Create Date: 2019-04-23 11:21:58.707598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "49bc99f4e27c"
down_revision = "f0700fa6a3ea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("riff_exercise_items", sa.Column("text_info", sa.String(length=255), nullable=True))
    op.add_column(
        "riff_exercise_items", sa.Column("use_alternate_chord_info_for_backingtrack", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("riff_exercise_items", "use_alternate_chord_info_for_backingtrack")
    op.drop_column("riff_exercise_items", "text_info")
    # ### end Alembic commands ###
