"""empty message

Revision ID: 578b94c63af4
Revises: 386683230f6d
Create Date: 2019-02-04 20:28:28.209409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578b94c63af4'
down_revision = '386683230f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riff_exercise_items', sa.Column('chord_info', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('riff_exercise_items', 'chord_info')
    # ### end Alembic commands ###
