"""empty message

Revision ID: 60b80747bce6
Revises: bd0c01cbc094
Create Date: 2020-10-27 13:17:50.612466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '60b80747bce6'
down_revision = 'bd0c01cbc094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('blog_intro', sa.String(), nullable=True),
    sa.Column('blog_publish', sa.Boolean(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    op.create_table('lesson_items',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('item_type', sa.Enum('TEXT', 'RIFF', 'RIFF_EXERCISE', 'BACKING_TRACK', 'YOUTUBE', name='lessonitemenum'), nullable=True),
    sa.Column('lesson_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('riff_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('riff_pitch', sa.String(length=3), nullable=True),
    sa.Column('riff_octave', sa.Integer(), nullable=True),
    sa.Column('riff_chord_info', sa.String(length=20), nullable=True),
    sa.Column('riff_exercise_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('backing_track_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('item_label', sa.String(length=255), nullable=True),
    sa.Column('item_text', sa.String(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['backing_track_id'], ['backing_tracks.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['riff_exercise_id'], ['riff_exercises.id'], ),
    sa.ForeignKeyConstraint(['riff_id'], ['riffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_items_id'), 'lesson_items', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_items_order_number'), 'lesson_items', ['order_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_items_order_number'), table_name='lesson_items')
    op.drop_index(op.f('ix_lesson_items_id'), table_name='lesson_items')
    op.drop_table('lesson_items')
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    op.drop_table('lessons')
    # ### end Alembic commands ###
