"""empty message

Revision ID: 631bf8722b25
Revises: 314daa387d52
Create Date: 2019-06-25 16:21:50.570670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631bf8722b25'
down_revision = '314daa387d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riff_exercise_items', sa.Column('chord_info_backing_track', sa.String(length=255), nullable=True))
    op.drop_column('riff_exercise_items', 'use_alternate_chord_info_for_backingtrack')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riff_exercise_items', sa.Column('use_alternate_chord_info_for_backingtrack', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('riff_exercise_items', 'chord_info_backing_track')
    # ### end Alembic commands ###
