"""introduce chords

Revision ID: 6d51df558ab3
Revises: 2e8d1f0237ea
Create Date: 2018-11-20 22:32:49.930166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d51df558ab3'
down_revision = '2e8d1f0237ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riffs', sa.Column('chord_info', sa.String(length=255), nullable=True))
    op.drop_column('riffs', 'backing_track_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riffs', sa.Column('backing_track_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('riffs', 'chord_info')
    # ### end Alembic commands ###
