"""empty message

Revision ID: 757548124b94
Revises: d662d2bfa83e
Create Date: 2022-03-23 22:48:56.788167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '757548124b94'
down_revision = 'd662d2bfa83e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riffs', sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'riffs', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'riffs', type_='foreignkey')
    op.drop_column('riffs', 'created_by')
    # ### end Alembic commands ###
