"""empty message

Revision ID: 983b4e76d8cb
Revises: 01fa911a4832
Create Date: 2018-08-11 00:45:21.690157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "983b4e76d8cb"
down_revision = "01fa911a4832"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "riff_exercises",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("is_global", sa.Boolean(), nullable=True),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_riff_exercises_id"), "riff_exercises", ["id"], unique=False)
    op.create_table(
        "riff_exercise_items",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("riff_exercise_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("riff_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["riff_exercise_id"], ["riff_exercises.id"],),
        sa.ForeignKeyConstraint(["riff_id"], ["riffs.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_riff_exercise_items_id"), "riff_exercise_items", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_riff_exercise_items_id"), table_name="riff_exercise_items")
    op.drop_table("riff_exercise_items")
    op.drop_index(op.f("ix_riff_exercises_id"), table_name="riff_exercises")
    op.drop_table("riff_exercises")
    # ### end Alembic commands ###
