"""empty message

Revision ID: a35761a62430
Revises: 1cd3b03edbe2
Create Date: 2022-01-12 01:56:26.535714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35761a62430'
down_revision = '1cd3b03edbe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backing_tracks', sa.Column('is_scale', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backing_tracks', 'is_scale')
    # ### end Alembic commands ###
