"""empty message

Revision ID: ad9b5f0b9acb
Revises: 309e6a50a5d5
Create Date: 2018-11-13 23:00:47.565548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad9b5f0b9acb'
down_revision = '309e6a50a5d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('riffs', 'multi_chord')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riffs', sa.Column('multi_chord', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
