"""empty message

Revision ID: b96c1a140fa3
Revises: cab5eae2b4e9
Create Date: 2019-02-19 16:03:13.219164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96c1a140fa3'
down_revision = 'cab5eae2b4e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riff_exercise_items', sa.Column('number_of_bars', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('riff_exercise_items', 'number_of_bars')
    # ### end Alembic commands ###
