"""empty message

Revision ID: bb7173894adb
Revises: 25496bfe382f
Create Date: 2019-01-07 14:04:05.806267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bb7173894adb"
down_revision = "25496bfe382f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("mail_announcements", sa.Boolean(), nullable=True))
    op.add_column("user", sa.Column("mail_offers", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "mail_offers")
    op.drop_column("user", "mail_announcements")
    op.drop_column("user", "created_at")
    # ### end Alembic commands ###
