"""empty message

Revision ID: bd0c01cbc094
Revises: ee5320f927de
Create Date: 2020-01-29 10:45:14.666121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bd0c01cbc094"
down_revision = "ee5320f927de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_preferences", "recent_lessons")
    op.drop_column("user_preferences", "recent_exercises")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_preferences",
        sa.Column("recent_exercises", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    )
    op.add_column(
        "user_preferences",
        sa.Column("recent_lessons", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
