"""empty message

Revision ID: c7628b49ba8b
Revises: 51909b2054cf
Create Date: 2019-09-14 20:21:13.556995

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c7628b49ba8b"
down_revision = "631bf8722b25"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("fs_uniquifier", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "fs_uniquifier")
    # ### end Alembic commands ###
