"""empty message

Revision ID: d015827d02ac
Revises: 3757f595a977
Create Date: 2019-03-09 21:34:04.342496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d015827d02ac"
down_revision = "3757f595a977"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("riff_exercise_items", sa.Column("modified_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("riff_exercise_items", "modified_at")
    # ### end Alembic commands ###
