"""empty message

Revision ID: d662d2bfa83e
Revises: 5a5a1576f2de
Create Date: 2022-03-22 23:26:04.377921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd662d2bfa83e'
down_revision = '5a5a1576f2de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riffs', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('riffs', 'is_public')
    # ### end Alembic commands ###
