"""Add tags

Revision ID: dfb9775450cb
Revises: 50ac624714d5
Create Date: 2018-12-08 00:33:39.382748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dfb9775450cb'
down_revision = '50ac624714d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('riff_tags',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('riff_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tag_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['riff_id'], ['riffs.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_riff_tags_id'), 'riff_tags', ['id'], unique=False)
    op.create_index(op.f('ix_riff_tags_riff_id'), 'riff_tags', ['riff_id'], unique=False)
    op.create_index(op.f('ix_riff_tags_tag_id'), 'riff_tags', ['tag_id'], unique=False)
    op.create_table('riff_exercise_tags',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('riff_exercise_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tag_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['riff_exercise_id'], ['riff_exercises.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_riff_exercise_tags_id'), 'riff_exercise_tags', ['id'], unique=False)
    op.create_index(op.f('ix_riff_exercise_tags_riff_exercise_id'), 'riff_exercise_tags', ['riff_exercise_id'], unique=False)
    op.create_index(op.f('ix_riff_exercise_tags_tag_id'), 'riff_exercise_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_riff_exercise_tags_tag_id'), table_name='riff_exercise_tags')
    op.drop_index(op.f('ix_riff_exercise_tags_riff_exercise_id'), table_name='riff_exercise_tags')
    op.drop_index(op.f('ix_riff_exercise_tags_id'), table_name='riff_exercise_tags')
    op.drop_table('riff_exercise_tags')
    op.drop_index(op.f('ix_riff_tags_tag_id'), table_name='riff_tags')
    op.drop_index(op.f('ix_riff_tags_riff_id'), table_name='riff_tags')
    op.drop_index(op.f('ix_riff_tags_id'), table_name='riff_tags')
    op.drop_table('riff_tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
