"""empty message

Revision ID: e8fb166b4e11
Revises: 86e8c23ee7c9
Create Date: 2020-01-09 15:53:39.570235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8fb166b4e11'
down_revision = '86e8c23ee7c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backing_tracks', sa.Column('complete', sa.Boolean(), nullable=True))
    op.add_column('backing_tracks', sa.Column('file', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_backing_tracks_file'), 'backing_tracks', ['file'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backing_tracks_file'), table_name='backing_tracks')
    op.drop_column('backing_tracks', 'file')
    op.drop_column('backing_tracks', 'complete')
    # ### end Alembic commands ###
