"""empty message

Revision ID: f0700fa6a3ea
Revises: 9dd401b4375a
Create Date: 2019-04-13 00:48:21.509800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0700fa6a3ea'
down_revision = '9dd401b4375a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riff_exercise_items', sa.Column('chord_info_alternate', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('riff_exercise_items', 'chord_info_alternate')
    # ### end Alembic commands ###
