"""empty message

Revision ID: f9e4b9a9d1e0
Revises: 0afe6098309b
Create Date: 2019-02-19 20:20:48.443495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e4b9a9d1e0'
down_revision = '0afe6098309b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riff_exercises', sa.Column('tempo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('riff_exercises', 'tempo')
    # ### end Alembic commands ###
